config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  #get 'reports/new'
  #get 'reports/edit'
  #get 'reports/show'
  get 'orders/index'
  get 'orders/new'
  get 'order_lines/new'
  get 'order_lines/index'
  #get 'orders/edit'
  #get 'orders/show'
  get 'publics/index'
  #post 'orders/order_summary'
  

  devise_scope :admin do
    authenticated :admin do
      resources :cashiers
      resources :products
      get 'orders/daily', to: 'orders#daily', as: :daily
      resources :reports
      root 'products#index', as: :authenticated_admin_root
    end
  end
  
  devise_scope :cashier do
    authenticated :cashier do
      post 'order_summary', to: 'orders#order_summary', as: :order_summary
      resources :orders
      resources :products
      resources :cashiers, :only => [:show]
      root 'orders#index', as: :authenticated_cashier_root
    end
  end
  
  devise_for :admins
  devise_for :cashiers
  root 'publics#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :cashiers
  has_many :products
  
  
  def to_s
    "#{email}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :admin
  has_many :orders
  
  def to_s
    "#{email}"
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :products, through: :order_lines
    has_many :order_lines
    belongs_to :cashier
    
    accepts_nested_attributes_for :order_lines
    accepts_nested_attributes_for :products
end
   

app/models/order_line.rb
class OrderLine < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
    # belongs_to :admin
    # belongs_to :cashier
    has_many :order_lines
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      authenticated_admin_root_path
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
  
  
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  before_action :set_cashier, only: [:edit, :show, :update, :destroy]
  
  def index
    @cashiers = Cashier.all
  end

  def new
    @cashier = current_admin.cashiers.new
  end
  
  def create
    @cashier = current_admin.cashiers.new(cashier_params)
    @cashier.status = true
    @cashier.commission = 0

    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully added."
    else
      render :new
    end
  end
  
  def edit
  end

  def show
    @cashier = Cashier.find_by(id: params[:id])
    
    @orders = Order.where(:cashier => @cashier)
    
    if !@cashier.present?
      redirect_to cashiers_path
    end
  end
  
  def destroy
    if @cashier.status == true
      @cashier.status = false
    else
      @cashier.status = true
    end
    
    if @cashier.save
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    end
  end
  
  def update
    if @cashier.update(cashier_params)
      redirect_to cashiers_path, notice: "Cashier successfully updated."
    else
      render :edit
    end
  end
  
  private
    def set_cashier
      @cashier = Cashier.find_by(id: params[:id])
      redirect_to cashiers_path, notice: "Cashier not found." if @cashier.nil?
    end
    
    def cashier_params
      params.require(:cashier).permit!
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:edit, :show, :update, :destroy]
  
  def order_summary
    @order = current_cashier.orders.new(order_params)
    i=0 
    @order.order_lines.each do |each_order|
      i += each_order.product.price * each_order.quantity
    end
    @order.total_price = i
    # @cashier.commission = 0.04 * current_cashier.orders.total_price
  end
  
  def daily
    @orders = Order.all
  end
  
  def index
    if current_cashier.status == true
      @orders = Order.all
    else
      sign_out current_cashier
      redirect_to publics_index_path
    end
  end

  def new
    @order = current_cashier.orders.new
  end
  
  def create
    @order = current_cashier.orders.new(order_params)
    
    if @order.save
      redirect_to @order, notice: "Order successfully added."
    else
      render :new
    end
  end
  
  def edit
  end

  def show
  end
  
  def update
    if @order.update(order_params)
      redirect_to orders_path, notice: "Order successfully updated."
    else
      render :edit
    end
  end
  
  def destroy
    if @order.status == true
      @order.status = false
    else
      @order.status = true
    end
    
    if @order.save
      redirect_to orders_path, notice: "Order successfully updated."
    end
  end
  
  private
    def set_order
      @order = Order.find_by(id: params[:id])
      redirect_to orders_path, notice: "Order not found." if @order.nil?
    end
    
    def order_params
      params.require(:order).permit!
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :show, :update, :destroy]
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    @product.status = true
    
    if @product.save
      redirect_to products_path, notice: "Product successfully added."
    else
      render :new
    end
  end
  
  def edit
  end

  def show
    @product = Product.find_by(id: params[:id])
    
    if !@product.present?
      redirect_to products_path
    end
  end
  
  def destroy
    if @product.status == true
      @product.status = false
    else
      @product.status = true
    end
    
    if @product.save
      redirect_to products_path, notice: "Product successfully updated."
    end
  end
  
  def update
    if @product.update(product_params)
      redirect_to products_path, notice: "Product successfully updated."
    else
      render :edit
    end
  end
  
  private
    def set_product
      @product = Product.find_by(id: params[:id])
      redirect_to products_path, notice: "Product not found." if @product.nil?
    end
    
    def product_params
      params.require(:product).permit!
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/cashiers/edit.html.erb
<!--
<h1>Edit Cashier</h1>

<%#= form_for @cashier, url: cashier_path do |f| %>
    Email: <%#= f.text_field :email %> <br>
    Password: <%#= f.text_field :password %> <br>
    Password Confirmation: <%#= f.text_field :password_confirmation %> <br>
    Name: <#%= f.text_field :name %> <br>

    <%#= f.submit "Submit" %>
<%# end %>
-->


<%= form_for @cashier do |f| %>
<div class="productContainer">
    <div class="row container">
        <h1><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit Cashier</h1>
    </div>
    
    <div class="row container">
          <div class="col-md-1">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
          </div>
          <div class="col-md-2">
            <%= f.text_field :email, class: "inputLogin", placeholder: "Email"%>
          </div>
      </div>
      
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
        </div>
        <div class="col-md-1">
          <%= f.password_field :password, class: "inputLogin", placeholder: "Password" %>
        </div>
      </div>
      
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
        </div>
        <div class="col-md-1">
          <%= f.password_field :password_confirmation, class: "inputLogin", placeholder: "Re-enter Password" %>
        </div>
      </div>
      
      <div class="row container">
          <div class="col-md-1">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          </div>
          <div class="col-md-2">
            <%= f.text_field :name, class: "inputLogin", placeholder: "Name"%>
          </div>
      </div>
      
      <br>
      <div class="row container">
        <div class="col-md-2 col-md-offset-1">
            <%= f.submit "Submit", class: "btn btn-prmry" %>
            <%= link_to "Back", products_path, class: "btn btn-danger" %>
        </div>
    </div>
</div>
<% end %>
      
      
      
      
<!--    <div class="row container">
        <div class="col-md-1">
            <h4>Name: </h4>
        </div>
        <div class="col-md-2">
            <%#= f.text_field :email, class: "input" %>
        </div>
    </div>
    <div class="row container">
        <div class="col-md-1">
            <h4>Password: </h4>
        </div>
        <div class="col-md-2">
            <%#= f.text_field :password, class: "input" %>
        </div>
    </div>
     <div class="row container">
        <div class="col-md-1">
            <h4>Password Confirmation: </h4>
        </div>
        <div class="col-md-2">
            <%#= f.text_field :password_confirmation, class: "input" %>
        </div>
    </div>
     <div class="row container">
        <div class="col-md-1">
            <h4>Name: </h4>
        </div>
        <div class="col-md-2">
            <%#= f.text_field :name, class: "input" %>
        </div>
    </div>
    <div class="row container">
        <div class="col-md-2 col-md-offset-1">
            <%#= f.submit "Submit", class: "btn btn-prmry" %>
            <%#= link_to "Back", products_path, class: "btn btn-back" %>
        </div>
    </div>
</div>
<%# end %>

app/views/cashiers/index.html.erb
<!--<h1>Cashiers</h1>
<%#= link_to "Add Cashier", new_cashier_path, class: "btn btn-primary" %>


<table class="table table-striped">
    <thead>
        <th>Name</th>
        <th>Email</th>
        <th>Created By</th>
        <th>Status</th>
        <th colspan="4"></th>
    </thead>
    <tbody>
        <%# @cashiers.each do |cashier| %>
            <tr>
                <td>
                    <%#= cashier.name %>
                </td>
                <td>
                    <%#= cashier.email %>
                </td>
                <td>
                    <%#= cashier.admin.email %>
                </td>
                <td>
                    <%#= cashier.status ? "Active" : "Inactive" %>
                </td>
                <td>
                    <%#= link_to "Edit", edit_cashier_path(cashier), class: "btn btn-primary" %>
                </td>
                <td>
                    <%#= link_to "View", cashier, class: "btn btn-primary" %>
                </td>
                <td>
                    <%#= link_to "Change status", cashier, method: :delete, class: "btn btn-primary" %>
                </td>
            </tr>
        <%# end %>
    </tbody>
</table>

-->





<h1>Cashiers</h1>
<div class="row container">
    <div class="col-md-2">
        <h4>Name</h4>
    </div>
    <div class="col-sm-3">
        <h4>Email</h4>
    </div>
    <div class="col-md-2">
        <h4>Created by</h4>
    </div>
    <div class="col-md-2">
        <h4>Status</h4>
    </div>
    <div class="col-md-3 addProduct">
        <button class="btn btn-prmry">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <%= link_to "Add Cashier", new_cashier_path, style: 'color:#FFFFFF; text-decoration: none;' %>
        </button>
    </div>
</div>

<% @cashiers.each do |cashier| %>
<div class="row container">
   	    <div class="col-md-2" id="cashierName"><%= cashier.name %></div>
        <div class="col-sm-3" id="cashierList"><%= cashier.email %></div>
   	    <div class="col-md-2" id="cashierList"><%= cashier.admin.email %></div>
       	<div class="col-md-1" id="cashierList"><%= cashier.status ? "Active" : "Inactive" %></div>
   		<div class="col-md-1" id="cashierBtn"><%= link_to "Edit", edit_cashier_path(cashier), class: "btn btn-primary" %></div>
   		<div class="col-md-1" id="cashierBtn"><%= link_to "View", cashier, class: "btn btn-info" %></div>
   		<div class="col-md-2" id="cashierBtn"><%= link_to "Change status", cashier, method: :delete, class: "btn btn-danger" %></div>
    <% end %>
</div>

app/views/cashiers/new.html.erb
<!--<h1>Add Cashier</h1>

<%#= form_for @cashier, url: cashiers_path do |f| %>
    Email: <%#= f.text_field :email %> <br>
    Password: <%#= f.text_field :password %> <br>
    Password Confirmation: <%#= f.text_field :password_confirmation %> <br>
    Name: <%#= f.text_field :name %> <br>
    <%#= f.submit "Submit" %>
<#% end %>
-->


<%= form_for @cashier, url: cashiers_path do |f| %>
<div class="row">
    <div class="col-md-4">
        <div class="cashierContainer">
            <div class="row container">
                <h1>New Cashier</h1>
            </div>
            
            <div class="row container">
                <div class="col-md-1">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                </div>
                <div class="col-md-2">
                    <%= f.text_field :email, class: "inputCashier", placeholder: "Email" %>  
                </div>
            </div>
            
            <div class="row container">
                <div class="col-md-1">
                    <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                </div>
                <div class="col-md-1">
                    <%= f.password_field :password, class: "inputCashier", placeholder: "Password" %>
                </div>
            </div>
            
            <div class="row container">
                <div class="col-md-1">
                    <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
                </div>
                <div class="col-md-1">
                    <%= f.password_field :password_confirmation, class: "inputCashier", placeholder: "Re-type Password" %>
                </div>
            </div>
            
            <div class="row container">
                <div class="col-md-1">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                </div>
                <div class="col-md-1">
                    <%= f.text_field :name, class: "inputCashier", placeholder: "Name" %>
                </div>
            </div>
            
            <div class="row container">
                <div class="col-md-3" style="margin-top:5px;text-align:right;">
                    <%= f.submit "Submit", class: "btn btn-prmry btn-sm"%>
                    <%= link_to "Back", cashiers_path, class: "btn btn-danger btn-sm" %>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/cashiers/show.html.erb
<!--<h1>Cashier</h1>

Name: <%#= @cashier.name %><br>
Email: <%#= @cashier.email %>
-->

<div class="showCashier">
    <div class="row container">
        <div class="col-md-4 showName">
            <h1><%= @cashier.name %></h1>
        </div>
    </div>
    <div class="row container">
        <div class="col-md-1">
            <h4>Email: </h4>
        </div>
        <div class="col-md-3">
            <h4>
            <%= @cashier.email %>
            </h4>
        </div>
    </div>
    <div class="row container">
        <div class="col-md-1">
            <h4>Admin: </h4>
        </div>
        <div class="col-md-3">
            <h4><%= if @cashier.admin then @cashier.admin.email else 'Anonymous' end%></h4>
        </div>
    </div>
    <div class="row container">
        <div class="col-md-1">
            <h4>Status: </h4>
        </div>
        <div class="col-md-3">
            <h4><%= if @cashier.status == true then 'Active' else 'Inactive' end %></h4>
        </div>
    </div>
    <br>

    <div class="row container" style="margin-right:200px">
        <div class="col-xs-1 center">Order ID</div>
        <div class="col-xs-2">Date Created</div>
        <div class="col-md-2">Total Price</div>
    </div>
    
    <% @orders.each do |a|%>
    <div class="row container" style="margin-right:200px">
        <div class="col-sm-1 center" id="showOrderC"><%= a.id %></div>
        <div class="col-xs-2 orderDate" id="showOrderC"><%= a.created_at%></div>
   	    <div class="col-sm-1 center" id="showOrderC"><%= a.total_price%></div>
    </div>
    <% end %>
</div>
           <!-- <table class="table">
                <tr><th>Order ID</th><th>Date Created</th><th>Total Price</th></tr>
                <%# @orders.each do |a|%>
                <tr>
                    <td><%#= a.id %></td>
                    <td><%#= a.created_at%></td>
                    <td><%#= a.total_price%></td>
                </tr>
                <%# end %>
            </table>
            
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Product System</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if admin_signed_in? %>
              <li>
                <%= link_to "Products", products_path %>
              </li>
              <li>
                <%= link_to "Cashiers", cashiers_path %>
              </li>
              <li>
                <%= link_to "Reports", daily_path %>
              </li>
            <% elsif cashier_signed_in? %>
              <%# if current_cashier.status == true %>
                <li>
                  <%= link_to "Orders", orders_path %>
                </li>
              <%# else %>
                <%# sign_out current_cashier %>
            <% end %>
          </ul>
          
          <p class="navbar-text pull-right">
          <% if admin_signed_in? %>
            Logged in as <strong><%= current_admin.email %></strong>.
            <% link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> 
            <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
          <% elsif cashier_signed_in? %>
              Logged in as <strong><%= current_cashier.email %></strong>.
              <% link_to 'Edit profile', edit_cashier_registration_path, :class => 'navbar-link' %> 
              <%= link_to "Logout", destroy_cashier_session_path, method: :delete, :class => 'navbar-link'  %>

          <% else %>
            <% link_to "Sign up", new_cashier_registration_path, :class => 'navbar-link'  %> 
            <% link_to "Login", new_cashier_session_path, :class => 'navbar-link'  %>            
          <% end %>
          </p>
          
        </div>
      </div>
    </nav>

    <div class="container">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_order_line_fields.html.erb
<div class="nested-fields">
    <div class="row container">
    <div class="col-md-4">
        <%# if @product.status == true %>
        <%# if order_line.product.status == true %>
            <%= f.association :product, class: "productMenu"  %>
        <%# else %>
            <%# order_line.destroy %>
        <%# end %>
        <%# end %>
    </div>
    <div class="col-md-2">
        <%= f.input :quantity, class: "quantity" %>
    </div>
    <div class="col-md-2">
        <%= link_to_remove_association "Remove product", f, class: "btn btn-danger remove" %>
    </div>
    </div>
    <br>
</div>

app/views/orders/index.html.erb
<h1>Orders</h1>
<%# if current_cashier.status == false %>
    <%# render 'publics/index' %>
<%# else %>
<% if @orders.empty? %>
    <small>
        <em>No orders made.</em>
            <button class="btn btn-prmry">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        <%= link_to "Add Order", new_order_path, style: 'color:#FFFFFF; text-decoration: none;' %>
    </button>
    </small>
<% else %>
<table class="table" style="text-transform:capitalize">
    <thead>
        <th>ID</th>
        <th>Cashier</th>
        <th>Total</th>
        <th>Cash</th>
        <th>Order</th>
        <th colspan="5"></th>
    </thead>
    <tbody>
        <% @count = 0 %>
        <% i = 0 %>
        <% @orders.each do |order| %>
            <tr>
                <td>
                    <%= @count += 1 %> 
                </td>
                <td>
                    <%= order.cashier.name %>
                </td>
                <td>
                    <%= order.total_price %>
                </td>
                <td>
                    <%= order.cash %>
                </td>
                <td>
                    <% order.order_lines.each do |x| %>
                        <ul>
                            <%= x.quantity %>
                            -
                            <%= x.product.name %>
                        </ul>
                    <% end %>
                </td>
                <td>
                    <% current_cashier.commission %>
                    <% if current_cashier == order.cashier %>
                        <% i += order.total_price * 0.04 %>
                        <% current_cashier.commission = i %>
                    <% end %>
                </td>
                <td>
                    <%= link_to "Show", order, class: "btn btn-info" %>
                </td>
                <td>
                    <%#= link_to "Print", order_summary, class: "btn btn-primary" %>
                </td>
            </tr>
        <% end %>
    </tbody>
    <h4>
    <%= current_cashier.name.capitalize %>'s (<%= current_cashier.email %>) commission: <%= current_cashier.commission %>
    </h4>
    <button class="btn btn-prmry">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        <%= link_to "Add Order", new_order_path, style: 'color:#FFFFFF; text-decoration: none;' %>
    </button>
    <br>
</table>
<% end %>
<%# end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= simple_form_for @order, url: order_summary_path do |f| %>
   
     <div class="hidin">
        
        <div class="links">
            <%= link_to_add_association 'Add Product', f, :order_lines, class: "btn btn-primary" %>
        </div>
        
        <div id="order_lines" class="hidden">
            <%= f.simple_fields_for :order_lines do |orderline| %>
                <%= render 'order_line_fields', f: orderline %>
                <%#if orderline.product.status == true%>
            <% end %>
        </div>
        
    </div>
    <br>
    <%= f.input :cash, as: :hidden %>
    <%= f.button :submit %>
    <%= link_to "Back", orders_path , class: "btn btn-danger" %>
<% end %>

app/views/products/index.html.erb
<!--<h1>Products</h1>
<%#= link_to "Add Product", new_product_path, class: "btn btn-primary" %>
<%# if @products.empty? %>
    <small>
        <em>No products made.</em>
    </small>
<%# else %>

<table class="table table-striped">
    <thead>
        <th>Name</th>
        <th>Price</th>
        <th>Status</th>
        <th colspan="3"></th>
    </thead>
    <tbody>
        <%# @products.each do |product| %>
            <tr>
                <td>
                    <%#= product.name %>
                </td>
                <td>
                    <%#= product.price %>
                </td>
                <td>
                    <%#= product.status ? "Active" : "Inactive" %>
                </td>
                <td>
                    <%#= link_to "Edit", edit_product_path(product), class: "btn btn-primary" %>
                </td>
                <td>
                    <%#= link_to "View", product, class: "btn btn-primary" %>
                </td>
                <td>
                    <%#= link_to "Change status", product, method: :delete, class: "btn btn-primary" %>
                </td>
            </tr>
        <%# end %>
    </tbody>
</table>
<%# end %>
-->

<h1>Products</h1>
<div class="row container">
    <div class="col-md-4">
        <h4>Name</h4>
    </div>
    <div class="col-md-2">
        <h4>Price</h4>
    </div>
    <div class="col-md-2">
        <h4>Status</h4>
    </div>
    <div class="col-md-4 addProduct">
        <button class="btn btn-prmry">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <%= link_to "Add Product", new_product_path, style: 'color:#FFFFFF; text-decoration: none;' %>
        </button>
    </div>
</div>
<div class="row container">
  	<% @products.each do |product| %>
   	    <div class="col-md-4" id="productList"><%= product.name %></div>
        <div class="col-md-2 php" id="productList"><%= product.price %></div>
   	    <div class="col-md-2" id="productList"><%= product.status ? "Active" : "Inactive" %></div>
       	<div class="col-md-1" id="productBtn"><%= link_to "Edit", edit_product_path(product), class: "btn btn-primary" %></div>
   		<div class="col-md-1" id="productBtn"><%= link_to "View", product, class: "btn btn-info" %></div>
   		<div class="col-md-2" id="productBtn"><%= link_to "Change status", product, method: :delete, class: "btn btn-danger" %></div>
    <% end %>
</div>

app/views/publics/index.html.erb
<!-- <h1>Welcome to our Product System!</h1> -->
<div class="mainContainer">

<div class="row">
  <div class="col-md-4">
    <div class="logIn">
      <div class="row container">
        <h1>Sign in as Admin</h1>
      </div>
      
      <%= form_for(:admin, :url => session_path(:admin)) do |f| %>
      <div class="row container">
          <div class="col-md-1">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
          </div>
          <div class="col-md-2">
            <%= f.text_field :email, class: "inputLogin", placeholder: "Email"%>
          </div>
      </div>
      
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
        </div>
        <div class="col-md-1">
          <%= f.password_field :password, class: "inputLogin", placeholder: "Password" %>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1" style="margin-top:10px">
          <%= f.submit 'Sign in', class: "btn btn-prmry btn-md" %>
        </div>
      </div>
      <div class="row container" style="margin-top:5px">
        <div class="col-md-3">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %> 
          <br>
          <%= link_to "Forgot your password?", new_password_path(:admin) %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-4 col-md-offset-1">
    <div class="logIn">
      <div class="row container">
        <h1>Sign in as Cashier</h1>
      </div>
        
      <%= form_for(:cashier, :url => session_path(:cashier)) do |f| %>
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
        </div>
        <div class="col-md-2">
          <%= f.text_field :email, class: "inputLogin", placeholder: "Email"%>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
        </div>
        <div class="col-md-1">
          <%= f.password_field :password, class: "inputLogin", placeholder: "Password" %>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1" style="margin-top:10px">
          <%= f.submit 'Sign in', class: "btn btn-prmry btn-md" %>
        </div>
      </div>
      <div class="row container" style="margin-top:10px">
        <div class="col-md-3">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %> 
          <br>
          <%= link_to "Forgot your password?", new_password_path(:admin) %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>